data:
  datapath: '/scratch3/wan410/operator_learning_data/Dedalus/ShallowWater'
  normalizer_path: '/scratch3/wan410/operator_learning_data/Dedalus/ShallowWater/normstat.pt'
  name: SW2D_Dedalus
  nx: 256
  ny: 128
  shuffle: True
  grid_form: spherical
  
model:
  name: multiscale_wavelet2d_periodic
  wave: haar
  dims: [32, 64, 128, 256, 512]
  in_chans: 4
  out_chans: 2
  use_efficient_attention: True
  efficient_layers: [0, 1, 2, 3]
  add_periodic_grid: true
  local_attention_size: 6
  external_grid: false

train:
  batchsize: 100
  epochs: 500
  milestones: [100, 200, 300, 400]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: /scratch3/wan410/operator_learning_model/SW2D_Dedalus/MSWT_spherical/
  save_name: MultiscaleWavelet2d_periodic-dim64-nlayers4.pt
  data_iter: 1
  eqn_iter: 0
  num_workers: 16

test_data:
  datapath: '/scratch3/wan410/operator_learning_data/pdearena/sw2d_pda/sw2d_pda_data_val.npy'
  total_num: 100
  nx: 96
  ny: 192
  nt: 87
  sub: 1
  sub_t: 1
  shuffle: False
