data:
  datapath: '/datasets/work/oa-turb-arc/work/multiscale_wavelet_transformers_Xuesong_ICML2026/benchmark/pdearena/sw2d_pda_data_train.npy'
  normalizer_path: '/datasets/work/oa-turb-arc/work/multiscale_wavelet_transformers_Xuesong_ICML2026/benchmark/pdearena/normstats.pt'
  name: SW2D
  total_num: 4000
  offset: 0
  n_sample: 100
  time_interval: 1
  nx: 96
  ny: 192
  nt: 87
  sub: 1
  sub_t: 1
  shuffle: True
  S2: 96
  T2: 88
  grid_form: periodic

model:
  name: multiscale_wavelet2d_periodic_patching
  wave: haar
  dims: [64, 64, 128, 512]
  in_chans: 6
  out_chans: 2
  use_efficient_attention: True
  efficient_layers: [0, 1, 2]
  add_periodic_grid: false
  local_attention_size: 8
  external_grid: false
  patch_size: 3


train:
  batchsize: 100
  epochs: 10_000
  milestones: [2_000, 4_000, 6_000, 8_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: /datasets/work/oa-turb-arc/work/multiscale_wavelet_transformers_Xuesong_ICML2026/checkpoint/SW2D_PDA/MSWT_patching2d_periodic/
  save_name: MultiscaleWavelet2d_periodic_patching-dim64-nlayers4.pt
  data_iter: 1
  eqn_iter: 0
  num_workers: 16

test_data:
  datapath: '/datasets/work/oa-turb-arc/work/multiscale_wavelet_transformers_Xuesong_ICML2026/benchmark/pdearena/sw2d_pda_data_val.npy'
  total_num: 100
  nx: 96
  ny: 192
  nt: 87
  sub: 1
  sub_t: 1
  shuffle: False
