data:
  datapath: '/scratch3/wan410/operator_learning_data/Dedalus/ShallowWater'
  normalizer_path: '/scratch3/wan410/operator_learning_data/Dedalus/ShallowWater/normstat.pt'
  name: SW2D_Dedalus
  nx: 256
  ny: 128
  shuffle: True
  grid_form: linear

model:
  name: saot
  space_dim: 2
  n_layers: 5
  n_hidden: 256
  dropout: 0.0
  n_head: 4
  Time_Input: False
  mlp_ratio: 1
  fun_dim: 2
  out_dim: 2
  slice_num: 32
  ref: 8
  unified_pos: 0
  is_filter: True


train:
  batchsize: 16
  epochs: 500
  milestones: [100, 200, 300, 400]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_dir: /scratch3/wan410/operator_learning_model/SW2D_Dedalus/SAOT2d_linear/
  save_name: SAOT2d-nlayers5-nhidden256.pt
  data_iter: 1
  eqn_iter: 0
  eval_step: 10

test_data:
  datapath: '/scratch3/wan410/operator_learning_data/pdearena/sw2d_pda/sw2d_pda_data_val.npy'
  total_num: 100
  nx: 96
  ny: 192
  nt: 87
  sub: 1
  sub_t: 1
  shuffle: False